# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('appointment_time', models.TimeField()),
                ('appointment_text', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_login', models.TextField(max_length=35)),
                ('host_password', models.TextField(max_length=100)),
                ('host_name', models.TextField(max_length=50)),
                ('host_cell_nr', models.TextField(max_length=15)),
                ('host_mail', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.TextField(max_length=35)),
                ('user_password', models.TextField(max_length=100)),
                ('user_name', models.TextField(max_length=50)),
                ('user_cell_nr', models.TextField(max_length=15)),
                ('user_mail', models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.Host'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarium.User'),
        ),
    ]
